apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: python-avafkljy
  janus-idp.io/tekton: python-avafkljy
  backstage.io/kubernetes-id: python-avafkljy
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: python-avafkljy
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
